{%set name = "zodburi" %}
{%set version = "2.2.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash = "3496a68a1548b39f55873980cf491e9ae95ca64cca66a619d44634f063f11582" %}
{%set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - zeo = zodburi.resolvers:client_storage_resolver
    - file = zodburi.resolvers:file_storage_resolver
    - zconfig = zodburi.resolvers:zconfig_resolver
    - memory = zodburi.resolvers:mapping_storage_resolver

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - zodb
    - zconfig
    - zeo

test:
  imports:
    - zodburi

about:
  home: https://github.com/Pylons/zodburi
  license: ZPL 2.1
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license_family: Other
  summary: 'Construct ZODB storage instances from URIs.'
  doc_url: https://zodburi.readthedocs.io/en/latest/
  dev_url: https://github.com/Pylons/zodburi

extra:
  recipe-maintainers:
    - pmlandwehr
