{% set name = "zodburi" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a7d7c68f83af27e3cec75d69a8136ef13e84a569c451885ffcbdd6371c63254

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - setuptools
    - zodb
    - zconfig
    - zeo

test:
  imports:
    - zodburi
  commands:
    - pip check
  requires: 
    - pip

about:
  home: https://github.com/Pylons/zodburi
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: Other
  summary: 'Construct ZODB storage instances from URIs.'
  doc_url: https://zodburi.readthedocs.io/en/latest/
  dev_url: https://github.com/Pylons/zodburi

extra:
  recipe-maintainers:
    - jan-janssen
