{% set name = "zodburi" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4359b964dffdae1e56a19124108d89f3730d15417260f828403cf05d6533cc41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - setuptools
    - zodb
    - zconfig
    - zeo

test:
  imports:
    - zodburi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Pylons/zodburi
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: Other
  summary: Construct ZODB storage instances from URIs.
  doc_url: https://zodburi.readthedocs.io/en/latest/
  dev_url: https://github.com/Pylons/zodburi

extra:
  recipe-maintainers:
    - jan-janssen
