travis:
  secure:
    BINSTAR_TOKEN: TNA8vBpJIB5XrG7kUQS23QGCAQcBoqphxeGFhLzaq/87fL7a6jrXcXtSaSvNPVYOcgf7HybfC/3RYsT1UmXLcxJrdhNVFeBdh+2WvjFe9+wMzB613dVdJUG5oEFtN4XZY0hTjyp+DHbww+Y4A+Fz1mSGWy6NPA++AtVgIcW8+lHKDvrJxxzjlMju9JjwXQ/5QJySp/SbzRSsHm7UTSpL9wxJWVxlMOiUycD4KZIeA4GcJq4UNDbelftiMFKocDGlFkk/d/zT1rAl6kE08/PCvucb66eR+3yVjfgV+BJK1Gju8Xo4S/05MT1/iFdB3XPpE3TPp0OgSCSkudQEZVX6WWytx2Borwfzz9p1BOFug/KFQs7o1VmqnH+G4fq9FBkHE0C8atpkt6n4m00KwdajuH0y4Q3//FaZ2ShSs6zmTYepzbzLgI1ybGQ5pPr66qflGP/9g2IWLAgHuCCTJ7782J5DMEM7sNL91Lu9Vgrj+lNxcF030w0e4cVHhzKUOpIkQMjDMszIY+hfuMVjW1vJjLtuVQ6/zPxjxUkOAiTjK+WX+P/K3YeZUgd5qu8IH0PXNBF8BlHQH3e+RP5H0wpIbiX6z4mTdGXFcoppLoSzskpSJs+Do273FCCyRD0kIMwZv2M8oIxTCxgUfAZLHTRWSDG3XPaLXYbbZ4l04TWi4Ms=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
