travis:
  secure:
    BINSTAR_TOKEN: cju4C7sDYZnYJRwX/0WwUXYeD9f04+XWeRoq622tThWoIfsDR8JtVicoXp6lQwMoYTi0+yGaoMp2Ine9g2kWXL5sRhPoHBLvSKLYy4eaxYt5Y9nuJWZWbd3HaCzPoV1fxYCbuPbQZQIO3WQWm51GnAMAvRCq4Zq3NJHmz7ag06gNJGZH924ObFKW6d+4c2NE+R+OgSnRulrxkUboYuQxCognj56ZZOEJ3ZMvX0XsOJXNt14cmyCUS0sneZtjsgcNkVgT0H55FCTyVykUulSHqkeEZ1d+jTBO8m5moK0pTQn8kTO5zgEc/G2urzaTuC/1Uu6uz9VK2674lxAN2UVbQ/aUqh7yV1jWvK4IqJHjz0+5ilkqNgKN2AWKESNlcOu2iv0XwHZiBhHci89bAnIq39xZMvwjYm4OwHnVu2IS9kqBHjvI41/SEHRrG4h1ypcAliGla0NEhSOUvTIz6V40Ot+ngNSSK6LzpTMw9S/I7y5PMHA5C+niaVIXioBVz/vDazX5aT59xgAnEdlRu1o1253zznDUxyCWTNplYnoAWreDl9mhJxPssTVbVFCxPitIXBY6ddHt5q69m/vhYj7yCZt/nTLbZS4uwiDCUwKC78pEfFUhYb0F47THVGdjObI+jDbAvfhFyA5fBiASAUA4zZW1Qyujr5KTiVkmmhEM408=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
